#pragma once
#include "../component/TransformComponent.h"
#include "../component/VisibleComponent.h"
#include "../component/DirectionalLightComponent.h"
#include "../component/PointLightComponent.h"
#include "../component/SphereLightComponent.h"
#include "../component/CameraComponent.h"
#include "../component/InputComponent.h"
#include "../component/EnvironmentCaptureComponent.h"
