#pragma once
#include "../Component/ModelComponent.h"
#include "../Component/LightComponent.h"
#include "../Component/CameraComponent.h"
#include "../Component/MeshComponent.h"
#include "../Component/MaterialComponent.h"
#include "../Component/TextureComponent.h"
#include "../Component/SkeletonComponent.h"
#include "../Component/AnimationComponent.h"