#define USE_ROW_MAJOR_MEMORY_LAYOUT
/* #undef USE_COLUMN_MAJOR_MEMORY_LAYOUT */

#define INNO_PLATFORM_WIN32
/* #undef INNO_PLATFORM_WIN64 */
/* #undef INNO_PLATFORM_LINUX64 */
/* #undef INNO_PLATFORM_MACOS */

#define INNO_RENDERER_OPENGL
/* #undef INNO_RENDERER_DX */
/* #undef INNO_RENDERER_VULKAN */
/* #undef INNO_RENDERER_METAL */

/* #undef BUILD_EDITOR */
#define BUILD_GAME
/* #undef BUILD_TEST */
