/* #undef USE_CLANG */

#define BUILD_GAME
/* #undef BUILD_EDITOR */
/* #undef BUILD_TEST */

#define USE_ROW_MAJOR_MEMORY_LAYOUT
/* #undef USE_COLUMN_MAJOR_MEMORY_LAYOUT */

/* #undef INNO_PLATFORM_WIN32 */
#define INNO_PLATFORM_WIN64
/* #undef INNO_PLATFORM_LINUX64 */
