#define USE_ROW_MAJOR_MEMORY_LAYOUT
/* #undef USE_COLUMN_MAJOR_MEMORY_LAYOUT */

/* #undef INNO_PLATFORM_WIN32 */
#define INNO_PLATFORM_WIN64
/* #undef INNO_PLATFORM_LINUX64 */
/* #undef INNO_PLATFORM_MACOS */

/* #undef INNO_RENDERER_OPENGL */
#define INNO_RENDERER_DX
/* #undef INNO_RENDERER_VULKAN */
/* #undef INNO_RENDERER_METAL */

/* #undef BUILD_EDITOR */
#define BUILD_GAME
/* #undef BUILD_TEST */
