add_library(TestLogicClient TestLogicClient.h TestLogicClient.cpp)
set_target_properties(TestLogicClient PROPERTIES FOLDER TestClient)
target_link_libraries(TestLogicClient Engine)

add_library(TestClientFactory TestClientFactory.cpp)
set_target_properties(TestClientFactory PROPERTIES FOLDER TestClient)
target_link_libraries(TestClientFactory TestLogicClient)
